export const cartActionType = ({
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_CART_ITEMS:'ADD_CART_ITEMS',
    REMOVE_CART_ITEM:'REMOVE_CART_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
})